# Commands to start on workspace startup
tasks:
  - name: hedera-example-contract-getter-setter
    init: |
      npm install -g
      # npm install @hedera/sdk
      # npm install dotenv
      # npm install -g solc
      open index.js
